apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  env: dev
  domain: myenvironment

configurations:
  - https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml

bases:
  - ../../base

resources:
  - .secrets.yaml

configMapGenerator:
  - name: my-app-configmap
    envs:
      - .env

patchesJson6902:
  - target:
      group: networking.istio.io
      version: v1beta1
      kind: Gateway
      name: my-app
    path: gateway.patch.yaml
  - target:
      group: cert-manager.io
      version: v1alpha3
      kind: Certificate
      name: my-app
      namespace: istio-system
    path: certificate.patch.yaml
  - target:
      group: networking.istio.io
      version: v1beta1
      kind: VirtualService
      name: my-app
    path: virtualservice.patch.yaml

images:
  - name: my-app
    newName: 232284734723.dkr.ecr.eu-west-1.amazonaws.com/k8s-dev-my-app
    newTag: latest