apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: my-system-domain
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/mhaddon/example-kubernetes-setup.git'
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true