apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: network-debugger
  labels:
    app: network-debugger
spec:
  selector:
    matchLabels:
      app: network-debugger
  template:
    metadata:
      labels:
        app: network-debugger
    spec:
      containers:
      - name: network-debugger
        image: nicolaka/netshoot:latest
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo 'ping'; sleep 10; done"]
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
