apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: default
spec:
  limits:
    - type: Container
      default:
        cpu: "150m"
        memory: 192Mi
      defaultRequest:
        cpu: "100m"
        memory: 64Mi
      max:
        cpu: "3000m"
        memory: 4Gi
