apiVersion: v1
kind: Namespace
metadata:
  name: gitops
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: gitops
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: "100m"
        memory: 128Mi
      max:
        cpu: "3000m"
        memory: 4Gi
