apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: istio-system
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: "100m"
        memory: 128Mi
      max:
        cpu: "3000m"
        memory: 4Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: kube-system
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: "100m"
        memory: 128Mi
      max:
        cpu: "3000m"
        memory: 4Gi