apiVersion: v1
kind: Namespace
metadata:
  name: tekton-pipelines
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
    istio-injection: enabled
---
apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: tekton-pipelines
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: "100m"
        memory: 128Mi
      max:
        cpu: "3000m"
        memory: 4Gi