apiVersion: cert-manager.io/v1alpha3
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory # https://letsencrypt.org/docs/rate-limits/ - https://tools.letsdebug.net/cert-search
    email: recruitment.mhaddon@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - dns01:
          route53:
            region: eu-west-1