apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: default-priority
value: 1
preemptionPolicy: Never
globalDefault: true
description: "This is the default priority class, any pods attached to this priority class will be deleted to make way for the higher priority-classes."
