- op: add
  path: /spec/source/helm
  value:
    values: |
      installCRDs: true
      replicaCount: 3
      extraArgs:
        - "--dns01-recursive-nameservers"
        - "8.8.8.8:53,1.1.1.1:53"
        - "--dns01-recursive-nameservers-only"
      serviceAccount:
        create: true
      securityContext:
        create: true
        enabled: true