apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader-service
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  source:
    repoURL: https://stakater.github.io/stakater-charts
    chart: reloader
    targetRevision: v0.0.68
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true