apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  env: dev

bases:
  - ../../base/

patchesJson6902:
  - target:
      group: cert-manager.io
      version: v1alpha3
      kind: ClusterIssuer
      name: letsencrypt-prod
      namespace: cert-manager
    path: letsencrypt-prod-issuer.patch.yaml
  - target:
      group: cert-manager.io
      version: v1alpha3
      kind: ClusterIssuer
      name: letsencrypt-staging
      namespace: cert-manager
    path: letsencrypt-staging-issuer.patch.yaml