apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  env: dev
  domain: common

bases:
  - ../../apps/argocd
  - ../../apps/descheduler
  - ../../apps/metrics-server
  - ../../apps/network-debugger
  - ../../apps/reloader
  - ../../apps/jaeger
  - ../../apps/prometheus

patchesStrategicMerge:
  - argo.patch.yaml