apiVersion: v1
kind: Namespace
metadata:
  name: my-application-domain
  labels:
    istio-injection: "enabled"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: my-application-domain
spec:
  limits:
    - type: Container
      default:
        cpu: "500m"
        memory: 512Mi
      defaultRequest:
        cpu: "100m"
        memory: 128Mi
      max:
        cpu: "3000m"
        memory: 4Gi
