apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: my-app
  namespace: istio-system
spec:
  secretName: my-app-certificate
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
