apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: gitops
spec:
  source:
    path: 'git-repositories/gitops-myenvironment-myapp/env/dev/'
    targetRevision: master