apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  env: dev

bases:
  - ../../base/

patchesJson6902:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: cluster-autoscaler-service
      namespace: gitops
    path: application.patch.yaml