apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: external-dns
          command:
            - "/bin/sh"
            - "-xc"
            - |-
              /bin/external-dns \
              --source=istio-gateway \
              --annotation-filter=aws.haddon.me/dns=expose \
              --domain-filter=${AWS_DOMAIN_FILTER} \
              --provider=aws \
              --aws-zone-type=public \
              --registry=txt \
              --txt-owner-id=/hostedzone/${AWS_PUBLIC_HOSTED_ZONE_ID}
          envFrom:
            - configMapRef:
                name: external-dns-configmap
      securityContext:
        fsGroup: 65534
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-internal
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns-internal
  template:
    metadata:
      labels:
        app: external-dns-internal
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: external-dns
          command:
            - "/bin/sh"
            - "-xc"
            - |-
              /bin/external-dns \
              --source=istio-gateway \
              --domain-filter=${AWS_DOMAIN_FILTER} \
              --provider=aws \
              --aws-zone-type=private \
              --registry=txt \
              --txt-owner-id=/hostedzone/${AWS_PRIVATE_HOSTED_ZONE_ID}
          envFrom:
            - configMapRef:
                name: external-dns-configmap
      securityContext:
        fsGroup: 65534