apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler-service
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  source:
    repoURL: https://kubernetes.github.io/autoscaler
    chart: cluster-autoscaler-chart
    targetRevision: 1.0.2
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true