apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  env: dev

namespace: kube-system

bases:
  - ../../base/

images:
  - name: external-dns
    newName: eu.gcr.io/k8s-artifacts-prod/external-dns/external-dns
    newTag: v0.7.3

configMapGenerator:
  - name: external-dns-configmap
    envs:
      - .env